Pl 131024 ceph multiversion rbd
flyingcircusio/backy pull request #28
Opened 2023-01-30 20:19 UTC by osnyx

Follow-up to #23.

This makes backy compatible to the Ceph Nautilus client tooling: rbd showmapped has now a different json output. It now returns a list of objects (dicts) decribing mappings, instead of an object (dictionary) already at the top level.
Keeps compatibility to previous Ceph versions by checking the Ceph version at runtime and differing in behaviour upon that.

Unit tests check behaviour based on outputs from Ceph Jewel, Luminous, and Nautilus.

Manually tested with #26 and #27 already merged.
Formatting issues have been (partially) neglected, as changes are going to be enforced by black through pre-commit rules anyways after merging #22.

## Release process

Impact: None, just wider compatibility.

Changelog:
- add compatibility to RBD backends running on Ceph Nautilus
- keep compatibility to RBD backends running on Ceph Jewel or Luminous

## Security implications

- [x] [Security requirements](https://wiki.flyingcircus.io/System_Development_Guideline#Security_requirement_principles_and_testing) defined?
  - [x] behaviour changes acommodating changed input formats must continue to support existing (legacy) systems
  - [x] test coverage of system must not decrease after change
  - [x] validation agains real-world data
- [ ] Security requirements tested? (EVIDENCE)
  - [x] unit tests covering all supported Ceph versions and their input formats
  - [x] test data acquired from real-world systems
  - [ ] test Nautilus compitability in development cluster
  - note: compatibility against Ceph Jewel and Luminous will **not** be tested manually due to the lack of a development clusters. The code covering these systems remains almost unchanged though and is covered by unit tests.

2023-03-07 12:30 UTC, osnyx commented
All tests are fixed now, ready for review.

One possible blocker: I see 1 backup failure in dev, verly likely due to corrupt parent revision data. We need to look into this before merging. PL-131339

2023-03-07 15:42 UTC, osnyx commented
@dhnasa and I think that the mentioned backup failure is not a new regression, but an extended case of #17 and the old revisions not having been distrusted despite failing their verifications in older backy versions.

2023-03-14 08:18 UTC, ctheune requested changes
looks good in general, really few small changes and we're good to go

2023-03-14 08:18 UTC, ctheune commented on src/backy/sources/ceph/rbd.py
> +            """The parser code for Ceph release Luminous and earlier."""
parse_mappings_pre_luminous

2023-03-14 08:18 UTC, ctheune commented on src/backy/sources/ceph/rbd.py
> +        def parse_mappings_current(mappings):
parse_mappings_since_luminous + comment is copy/pasta :)

2023-03-14 08:57 UTC, ctheune approved these changes
lgtm

2023-03-14 08:57 UTC, merged